apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-routing
  namespace: default                   
  labels:
    managed-by: my-kube-prometheus-stack   
spec:
  route:
    receiver: drop-others                    
    groupBy: ['alertname','namespace','service']
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 1h
    routes:
      # critical -> Slack critical
      - receiver: slack-critical
        matchers:
          - name: severity
            value: critical
      # warning -> Slack warning
      - receiver: slack-warning
        matchers:
          - name: severity
            value: warning

  receivers:
    # Receiver for CRITICAL
    - name: slack-critical
      slackConfigs:
        - apiURL:                               
            name: slack-webhooks
            key: critical_url
          sendResolved: true   
          title: >-
            [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} — {{ .CommonLabels.namespace }}
          text: >-
            *Severity*: {{ .CommonLabels.severity }}
            *App*: {{ if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}-{{ end }}
            *Summary*: {{ if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary }}{{ else }}-{{ end }}
            *Description*: {{ if .CommonAnnotations.description }}{{ .CommonAnnotations.description }}{{ else }}-{{ end }}
            *Link*: <{{ .ExternalURL }}|Alertmanager>
          color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

    # Receiver for WARNING
    - name: slack-warning
      slackConfigs:
        - apiURL:
            name: slack-webhooks
            key: warning_url
          sendResolved: true
          title: >-
            [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} — {{ .CommonLabels.namespace }}
          text: >-
            *Severity*: {{ .CommonLabels.severity }}
            *App*: {{ if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}-{{ end }}
            *Summary*: {{ if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary }}{{ else }}-{{ end }}
            *Description*: {{ if .CommonAnnotations.description }}{{ .CommonAnnotations.description }}{{ else }}-{{ end }}
            *Link*: <{{ .ExternalURL }}|Alertmanager>
          color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

    # "Trash can" receiver (avoids noise from unmatched sources)
    - name: drop-others
