name: Build Test and Push

on:
    pull_request:
        branches:
            - staging
            - main
        types:
            - closed

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.tag.outputs.TAG }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Google Cloud Authentication
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY_GKE }}

            - name: Google Cloud SDK setup
              uses: google-github-actions/setup-gcloud@v2

            - name: Docker and Artifact Registry configuration
              run: |
                gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

            - name: Image tag definition
              id: tag
              run: |
                echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Build Docker image
              run: |
                docker build -f docker/Dockerfile -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/app-observability:${{ steps.tag.outputs.TAG }} .

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: '${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/app-observability:${{ steps.tag.outputs.TAG }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL'

            - name: Push Docker image
              run: |
                docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/app-observability:${{ steps.tag.outputs.TAG }}
